[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "prettytable>=3.16.0",
    "pygame>=2.6.1",
    "streamlit>=1.47.1",
]
